services:
  project-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: project_service_db
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman123
    ports:
      - "5431:5432"

  task-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_service_db
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman123
    ports:
      - "5432:5432"

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman123
    ports:
      - "5433:5432"

  comment-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: comment_service_db
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman123
    ports:
      - "5434:5432"

  notification-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman123
    ports:
      - "5435:5432"
