server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # Project Service Routes
        - id: project-service
          uri: http://localhost:3001
          predicates:
            - Path=/api/projects/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

        # Task Service Routes
        - id: task-service
          uri: http://localhost:3002
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

        # User Service Routes
        - id: user-service
          uri: http://localhost:3003
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

        # Comment Service Routes
        - id: comment-service
          uri: http://localhost:3004
          predicates:
            - Path=/api/comments/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

        # Notification Service Routes
        - id: notification-service
          uri: http://localhost:3005
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG 